WB/WB/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.conf.urls import url
from .views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home_view, name='Home'),
    path("send/",include('send.urls')),
    #url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    #url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

WB/send/urls.py
from django.urls import path
from .views import send_view,add_one_view,add_csv_view,send_attachment_view,welcome_view,list_phone_number_view,number_delete_view

urlpatterns = [
    path("",welcome_view,name="welcome"),
    path("message",send_view,name="send"),
    path("add_one",add_one_view,name="one"),
    path("add_csv",add_csv_view,name="csv"),
    path("attachment",send_attachment_view,name="attachment"),
    path("phone_numbers",list_phone_number_view,name="phone_number"),
    path("<int:id>/number_delete",number_delete_view,name="number_delete"),
]

WB/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.conf.urls import url
from .views import home_view
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',home_view, name='Home'),
    path('scan',home_view, name='scanQR'),
    path("send/",include('send.urls')),
    path('', views.LoginView.as_view(template_name='login.html'), name="login"),
    path('logout/', views.LogoutView.as_view(template_name='logout.html'), name="logout"),

    #url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    #url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

send/urls.py
from django.urls import path
from .views import send_view,add_one_view,add_csv_view,send_attachment_view,welcome_view,list_phone_number_view,number_delete_view

urlpatterns = [
    path("",welcome_view,name="welcome"),
    path("message",send_view,name="send"),
    path("add_one",add_one_view,name="one"),
    path("add_csv",add_csv_view,name="csv"),
    path("attachment",send_attachment_view,name="attachment"),
    path("phone_numbers",list_phone_number_view,name="phone_number"),
    path("<int:id>/number_delete",number_delete_view,name="number_delete"),
]

WB/send/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.
class Whatsapp_Numbers(models.Model):
    number = PhoneNumberField(null=False,blank=False)
    user = models.CharField(max_length=32)

    def __str__(self):
        return (self.user)+str(self.number) 

class Read_csv(models.Model):
    File = models.FileField(upload_to="Csv_file")

    def __str__(self):
        return str(self.File)

class Attachment(models.Model):
    File = models.FileField(upload_to="Attachments")

    def __str__(self):
        return str(self.File)

send/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.
class Whatsapp_Numbers(models.Model):
    number = PhoneNumberField(null=False,blank=False)
    user = models.CharField(max_length=32)

    def __str__(self):
        return str(self.number) 

class Read_csv(models.Model):
    File = models.FileField(upload_to="Csv_file")

    def __str__(self):
        return str(self.File)

class Attachment(models.Model):
    File = models.FileField(upload_to="Attachments")

    def __str__(self):
        return str(self.File)

WB/send/forms.py
from django import forms
from phonenumber_field.formfields import PhoneNumberField
from .models import Read_csv,Attachment

class Option(forms.Form):
    text = forms.CharField(widget=forms.Textarea(attrs={'cols': 120}))
    
class Add_number(forms.Form):
    Phone_No = PhoneNumberField()

class Add_csv(forms.ModelForm):
    class Meta:
        model = Read_csv
        fields = ("File",)

class Add_Attachment(forms.ModelForm):
    class Meta:
        model = Attachment
        fields = ("File",)

send/forms.py
from django import forms
from phonenumber_field.formfields import PhoneNumberField
from .models import Read_csv,Attachment

class Option(forms.Form):
    text = forms.CharField(widget=forms.Textarea(attrs={'cols': 120}))
    
class Add_number(forms.Form):
    Phone_No = PhoneNumberField()

class Add_csv(forms.ModelForm):
    class Meta:
        model = Read_csv
        fields = ("File",)

class Add_Attachment(forms.ModelForm):
    class Meta:
        model = Attachment
        fields = ("File",)

WB/send/views.py
from django.shortcuts import render,redirect,HttpResponse
from time import sleep
from .forms import Option,Add_number,Add_csv,Add_Attachment
from .saved_contacts import send_to_saved
from .unsaved_contacts import whatsapp_login,send_to_unsaved,quits,send_attachment_to_unsavaed
import csv
from .models import Whatsapp_Numbers,Read_csv,Attachment
import os
from pathlib import Path
from django.contrib import messages
# Create your views here.

def welcome_view(request):
    whatsapp_login()
    return render(request,r"send\welcome.html")

def list_phone_number_view(request):
    obj=Whatsapp_Numbers.objects.all()
    return render(request,r"send\phone_numbers.html",{"numbers":obj})

def number_delete_view(request,id):
    obj=Whatsapp_Numbers.objects.get(pk=id)
    if request.method == 'POST':
        obj.delete()
        return redirect('phone_number')
    context = {
        'number': obj
    }
    return render(request,'send/number_delete.html',context)

def send_view(request):
    if request.method=="POST":
        etext=Option(request.POST)
        text=request.POST.get("text")
        lst=Whatsapp_Numbers.objects.filter(user="sib").values_list("number")
        numbers=[]
        for number in lst:
            number=str(number)
            a=number[3:15]
            numbers.append(a)
        for number in numbers:
            send_to_unsaved(number,text,1)
            sleep(1)
        messages.success(request,"All messages sent.")
        return redirect("send")
    else:
        send=Option
        return render(request,r"send\send_message.html",{"form":send})

def send_attachment_view(request):
    if request.method=="POST":
        obj = Add_Attachment(request.POST,request.FILES)
        if obj.is_valid(): 
            obj.save()
            name=request.FILES['File']
            dir=Path(__file__).resolve().parent.parent
            address=f"{dir}\media\Attachments\{name}"
            lst=Whatsapp_Numbers.objects.filter(user="sib").values_list("number")
            numbers=[]
            for number in lst:
                number=str(number)
                a=number[3:15]
                numbers.append(a)
            for number in numbers:
                send_attachment_to_unsavaed(number,address)
                sleep(1)
            messages.success(request,"All attachment sent.")
            os.remove(address)
            return redirect("attachment")
        else:
            print("error")
            return redirect("attachment")
    else:
        attach=Add_Attachment
        return render(request,r"send\send_attachment.html",{"form":attach})

def add_one_view(request):
    if request.method == "POST":
        number=request.POST.get("Phone_No")
        auth="sib"
        if int(number[3])>5:
            new_entry=Whatsapp_Numbers(number=number,user=auth)
            new_entry.save()
            return redirect("send")
        else:
            messages.error(request,"invalid number")
            return redirect("one")
    else:
        num_form=Add_number
        return render(request , r"send\add_one.html" , {"form":num_form})

def add_csv_view(request):
    if request.method == "POST":
        ext = os.path.splitext(str(request.FILES['File']))[1]
        if ext != ".csv":
            messages.error(request,"Not a csv file.")
            print("error")
            return redirect("csv")
        else:
            obj = Add_csv(request.POST,request.FILES)
            print(obj.is_valid)
            if obj.is_valid(): 
                obj.save()
                name=request.FILES['File']
                address=f"media\Csv_file\{name}"
                lst,count=read_file(address)
                for number in lst:
                    whats_obj=Whatsapp_Numbers(number=number,user="sib")
                    whats_obj.save()
                os.remove(address)

                if count != 0:
                    messages.warning(request,"There are some invalid numbers.")
                return redirect("csv")
            else:
                messages.error(request,"Invalid File")
                return redirect("csv")
    else:
        csv_form=Add_csv
        return render(request,r"send\add_csv.html",{"form":csv_form})



def read_file(csv_f):
    with open(csv_f) as file:
        numbers = csv.reader(file)
        country_code="+91"
        next(numbers)
        lst=[]
        count=0
        for number in numbers:
            number=str(number)
            if len(number) == 14 and int(number[2])>5:
                a=country_code+str(number[2:12])
                lst.append(a)
            else:
                count=count+1
        return lst,count

send/views.py
from django.shortcuts import render,redirect,HttpResponse
from time import sleep
from .forms import Option,Add_number,Add_csv,Add_Attachment
from .saved_contacts import send_to_saved
from .unsaved_contacts import whatsapp_login,send_to_unsaved,quits,send_attachment_to_unsavaed
import csv
from .models import Whatsapp_Numbers,Read_csv,Attachment
import os
from pathlib import Path
from django.contrib import messages
# Create your views here.

def welcome_view(request):
    if not check_user(request):
        return render(request,r"send\please_login.html")
    whatsapp_login()
    return render(request,r"send\welcome.html")

def list_phone_number_view(request):
    if not check_user(request):
        return render(request,r"send\please_login.html")
    obj=Whatsapp_Numbers.objects.filter(user=request.user)
    return render(request,r"send\phone_numbers.html",{"numbers":obj})

def number_delete_view(request,id):
    if not check_user(request):
        return render(request,r"send\please_login.html")
    obj=Whatsapp_Numbers.objects.filter(pk=id)
    if not check_same(request,obj):
        return redirect("send")
    if request.method == 'POST':
        obj.delete()
        return redirect('phone_number')
    context = {
        'number': obj
    }
    return render(request,'send/number_delete.html',context)

def send_view(request):
    if not check_user(request):
        return render(request,r"send\please_login.html")
    if request.method=="POST":
        etext=Option(request.POST)
        text=request.POST.get("text")
        lst=Whatsapp_Numbers.objects.filter(user="request.user").values_list("number")
        numbers=[]
        for number in lst:
            number=str(number)
            a=number[3:15]
            numbers.append(a)
        for number in numbers:
            send_to_unsaved(number,text,1)
            sleep(1)
        messages.success(request,"All messages sent.")
        return redirect("send")
    else:
        send=Option
        return render(request,r"send\send_message.html",{"form":send})

def send_attachment_view(request):
    if not check_user(request):
        return render(request,r"send\please_login.html")
    if request.method=="POST":
        obj = Add_Attachment(request.POST,request.FILES)
        if obj.is_valid(): 
            obj.save()
            name=request.FILES['File']
            dir=Path(__file__).resolve().parent.parent
            address=f"{dir}\media\Attachments\{name}"
            lst=Whatsapp_Numbers.objects.filter(user="request.user").values_list("number")
            numbers=[]
            for number in lst:
                number=str(number)
                a=number[3:15]
                numbers.append(a)
            for number in numbers:
                send_attachment_to_unsavaed(number,address)
                sleep(1)
            messages.success(request,"All attachment sent.")
            os.remove(address)
            return redirect("attachment")
        else:
            print("error")
            return redirect("attachment")
    else:
        attach=Add_Attachment
        return render(request,r"send\send_attachment.html",{"form":attach})

def add_one_view(request):
    if not check_user(request):
        return render(request,r"send\please_login.html")
    if request.method == "POST":
        number=request.POST.get("Phone_No")
        auth=request.user
        if int(number[3])>5:
            new_entry=Whatsapp_Numbers(number=number,user=auth)
            new_entry.save()
            return redirect("send")
        else:
            messages.error(request,"invalid number")
            return redirect("one")
    else:
        num_form=Add_number
        return render(request , r"send\add_one.html" , {"form":num_form})

def add_csv_view(request):
    if not check_user(request):
        return render(request,r"send\please_login.html")
    if request.method == "POST":
        ext = os.path.splitext(str(request.FILES['File']))[1]
        if ext != ".csv":
            messages.error(request,"Not a csv file.")
            print("error")
            return redirect("csv")
        else:
            obj = Add_csv(request.POST,request.FILES)
            print(obj.is_valid)
            if obj.is_valid(): 
                obj.save()
                name=request.FILES['File']
                address=f"media\Csv_file\{name}"
                lst,count=read_file(address)
                for number in lst:
                    whats_obj=Whatsapp_Numbers(number=number,user=request.user)
                    whats_obj.save()
                os.remove(address)

                if count != 0:
                    messages.warning(request,"There are some invalid numbers.")
                return redirect("csv")
            else:
                messages.error(request,"Invalid File")
                return redirect("csv")
    else:
        csv_form=Add_csv
        return render(request,r"send\add_csv.html",{"form":csv_form})

def  check_user(request):
    if request.user.is_authenticated:
        return True
    else:
        return False

def check_same(request,obj):
    if str(obj[0].user)==str(request.user):
        return True
    else:
        return False

def read_file(csv_f):
    with open(csv_f) as file:
        numbers = csv.reader(file)
        country_code="+91"
        next(numbers)
        lst=[]
        count=0
        for number in numbers:
            number=str(number)
            if len(number) == 14 and int(number[2])>5:
                a=country_code+str(number[2:12])
                lst.append(a)
            else:
                count=count+1
        return lst,count

send/templates/send/add_csv.html
{% extends "base.html" %} 
{% block title %}
      Add Csv File
{% endblock %}

{% block content %}
<div class="page-wrapper">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="page-breadcrumb">
        <div class="row">
            <div class="col-5 align-self-center">
                <h4 class="page-title">Send Bulk Messages</h4>

            </div>

        </div>
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <!-- basic table -->
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-body">

                        <div class="col-12">
                            {% if messages %}
                            <ul class="messages">
                                {% for message in messages %}
                                <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
                                {% endfor %}
                            </ul>
                          {% endif %}

                            
                        </div>
                  
                        <h4 class="card-title"></h4>
                            <h6>Add number through csv file</h6>
                            <pre>Please only upload file with extension csv
                            </pre>
                        <form class="form" method="POST" enctype="multipart/form-data" >
                                {% csrf_token %}
                                {{form.as_p }}
                            <div class="col-sm-12" style="margin: auto;text-align: center;">
                                <button type="submit" class="btn btn-info">Upload File</button>
                            </div>


                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

send/templates/send/add_one.html
{% extends "base.html" %} 
{% block title %}
      Add Number
{% endblock %}

{% block content %}
<div class="page-wrapper">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="page-breadcrumb">
        <div class="row">
            <div class="col-5 align-self-center">
                <h4 class="page-title">Send Bulk Messages</h4>

            </div>

        </div>
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <!-- basic table -->
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <div class="col-12">
                            {% if messages %}
                                    <div class="alert bg-{{ message.tags }} text-white">
                                        <h4> {{ message }}  </h4>
                                    </div>
                                    {% endif %}
                        </div>
                  
                        <h4 class="card-title"></h4>
                            <h6>Add single number</h6>
                            <pre>Please write the number with the country code.
Like for india add +91**********
                            </pre>
                        <form class="form" method="POST" >
                                {% csrf_token %}

                            {{form.as_p }}
                            <div class="col-sm-12" style="margin: auto;text-align: center;">
                                <button type="submit" class="btn btn-info">Add number</button>
                            </div>


                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

send/templates/send/number_delete.html
{% extends "base.html" %} 
{% block title %}
      Delete Number
{% endblock %}

{% block content %}
<div class="page-wrapper">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="page-breadcrumb">
        <div class="row">
            <div class="col-5 align-self-center">
                <h4 class="page-title">Send Bulk Messages</h4>

            </div>

        </div>
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <!-- basic table -->
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <div class="col-12">
        <div>
            <form action='number_delete' method='POST'>
                {% csrf_token %}
                <h1>Are you sure you want to delete the Number???</h1>
                <p><input value='Delete' type="submit"/>  <a href='{% url "phone_number" %}'>Cancel</a></p>

            </form>
        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

send/templates/send/phone_numbers.html
{% extends "base.html" %}
{% block title %}
      List of Phone Numbers
{% endblock %}

{% block content %}
<div class="page-wrapper">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="page-breadcrumb">
        <div class="row">
            <div class="col-5 align-self-center">
                <h4 class="page-title">Send Bulk Messages</h4>

            </div>

        </div>
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <!-- basic table -->
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <div class="col-12">
                            {% if numbers %}
                            <table>
                                <tr>
                                    <th>Phone Numbers</th>
                                    <th>Keys</th>
                                </tr>
                                {% for number in numbers %}
                                    <tr>
                                        <td>
                                            <h3>{{number.number}}</h3>
                                        </td>
                                        <td>
                                            <a href="{% url 'number_delete' number.pk %}" class="btn btn-primary btn-lg active"  style="font-size: medium;">Delete</a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </table>
                            {% else %}
                            <a href="{% url 'one' %}" class="btn btn-primary btn-lg active"  style="font-size: medium;">add Number</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

send/templates/send/please_login.html
{% load static %}
<!DOCTYPE html>
<html dir="ltr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/images/favicon.png' %}">
    <title> InfoTech</title>
    <!-- Custom CSS -->
    <link href="{% static 'dist/css/style.min.css' %}" rel="stylesheet">
  
</head>

<body>
    <br><br><br>
<div class="form-group text-center">
    <h4>To go further please Login!!!</h4>
    <a style="background:#09a709;border:#09a709;height: 50px;width: 100px;border-radius: 5px;" class="btn btn-info mt-3 p-15 pl-4 pr-4 mb-3" href="{% url 'login' %}">
        <b>Login</b></a>
</div>
</body>
</html>

send/templates/send/send_message.html
{% extends "base.html" %} 
<!-- {% load static %} -->
{% block title %}
      Send messages
{% endblock %}

{% block content %}
<div class="page-wrapper">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="page-breadcrumb">
        <div class="row">
            <div class="col-5 align-self-center">
                <h4 class="page-title">Send Bulk Messages</h4>

            </div>

        </div>
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <!-- basic table -->
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-body">

                        <div class="col-12">
                            <!-- {% if messages %}
                                    <div class="alert bg-{{ message.tags }} text-white">
                                        <h4> {{ message }}  </h4>
                                    </div>
                                    {% endif %} -->
                                   
                                        {% if messages %}
                                          <ul class="messages">
                                              {% for message in messages %}
                                              <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
                                              {% endfor %}
                                          </ul>
                                        {% endif %}
                                   
                        </div>

                     
                  
                        <!-- <h4 class="card-title">Add Advertisements</h4> -->
                        <h4 class="card-title"></h4>
                            <h6>Send Messages On the Go!!</h6>
                        <form class="form" method="POST" >
                                {% csrf_token %}
                            <!-- <div class="form-group mt-4 row">
                                <label for="example-month-input2" class="col-sm-3 col-form-label">Select Category</label>
                                <div class="col-sm-6">
                                    <select required name="option" id="id_option" class="custom-select col-12">
                                        <option selected="">Select Category</option>
                                        <option >Saved</option>
                                        <option >Unsaved</option>
                                      

                                       

                                    </select>
                                </div>
                            </div>

                        
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">Message To Send</label>
                                <div class="col-sm-6">
                                    <input class="form-control" type="text" name="text" id="id_text" required>
                                </div>
                            </div> -->

                            <!-- {% csrf_token %} -->
                            {{form.as_p }}
                            <div class="col-sm-12" style="margin: auto;text-align: center;">
                                <button type="submit" class="btn btn-info">Start Sending</button>
                            </div>


                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

send/templates/send/welcome.html
{% extends "base.html" %}
{% block title %}
      Opening Automated Browser
{% endblock %} 

{% block content %}
<div class="page-wrapper">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="page-breadcrumb">
        <div class="row">
            <div class="col-5 align-self-center">
                <h4 class="page-title">Send Bulk Messages</h4>

            </div>

        </div>
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <!-- basic table -->
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <h1>welcome to the WhatsBulk!!!</h1>
                    <p>Please avoid opening to more than one automated browsers</p>
                </div>
            </div>
        </div>

    </div>
{% endblock %}